#directory definations

#command definations
MAKE  = make

ifndef release
export OPSCFLAGS = -O0
export OPSDEF    = -DDEBUG
else
export OPSCFLAGS = -O2
endif

CXX		 = g++ -ftemplate-depth-50 -Wall -g $(OPSCFLAGS)
CXXFLAGS = -fpermissive
RM		 = rm -f
CP		 = cp
AR		 = ar rcs

#rule definations

.SUFFIXES:  .cxx
.cpp.o:
	$(CXX)  $(CXXFLAGS) -o $@ -c $<
.cxx.o:
	$(CXX)  $(CXXFLAGS) -o $@ -c $<
.cc.o:
	$(CXX)  $(CXXFLAGS) -o $@ -c $<

