#ifndef __CODE_DEFS_H__
#define __CODE_DEFS_H__

//The error code or result_t type value 
typedef enum ErrorCode
{
    ERR_CODE_INVALID = -2,
    ERR_CODE_PARAMS_INVALID = -1,
    ERR_CODE_OK = 0,
    ERR_CODE_SUCCESSED = ERR_CODE_OK,
    ERR_CODE_CREATE_LEVEL_FAILED,
    ERR_CODE_CREATE_TRACER_FAILED,
    ERR_CODE_CREATE_CONNECTION_MGR_FAILED,
    ERR_CODE_CREATE_CONNECTION_FAILED,
    ERR_CODE_CREATE_STREAM_FAILED,
    ERR_CODE_REQ_SUBMIT_FAILED,
    ERR_CODE_ADD_REQ_TO_WAIT_FAILED,
    ERR_CODE_OVERLOAD,
    ERR_CODE_NOT_EXIST,
    ERR_CODE_REQ_SERVER_INFO_FAILED,
    ERR_CODE_ADD_REQ_FAILED,
    ERR_CODE_NEW_SESSION_FAILED,
    ERR_CODE_SESSION_CREATE_FAILED,
    ERR_CODE_SESSION_START_FAILED,
    ERR_CODE_TASK_NOT_EXIST,
    ERR_CODE_MEMORY_NOT_ENOUGH,
    ERR_CODE_UNKOWN,
}result_t;


#endif/*__CODE_DEFS_H__*/
